[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@layerzero/v2/packages/evm/oapp=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/contracts/oapp",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
